CREATE DATABASE IF NOT EXISTS busegg_site_dev DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE busegg_site_dev;

CREATE TABLE IF NOT EXISTS admin_user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(64) NOT NULL UNIQUE COMMENT '登录账号',
  password VARCHAR(255) NOT NULL COMMENT '加密密码',
  nickname VARCHAR(64) NOT NULL COMMENT '昵称',
  phone VARCHAR(32) NULL COMMENT '手机号',
  role_code VARCHAR(32) NOT NULL DEFAULT 'SUPER_ADMIN' COMMENT '角色编码',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用，0禁用',
  last_login_time DATETIME NULL COMMENT '最后登录时间',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='管理员';

CREATE TABLE IF NOT EXISTS leads (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(64) NOT NULL COMMENT '姓名',
  phone VARCHAR(32) NOT NULL COMMENT '联系电话',
  type VARCHAR(64) NOT NULL COMMENT '合作类型',
  message VARCHAR(1000) NULL COMMENT '留言',
  source VARCHAR(64) NOT NULL DEFAULT 'website' COMMENT '来源',
  status VARCHAR(32) NOT NULL DEFAULT '未处理' COMMENT '处理状态',
  remark VARCHAR(1000) NULL COMMENT '跟进备注',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  INDEX idx_leads_phone (phone),
  INDEX idx_leads_type (type),
  INDEX idx_leads_status (status),
  INDEX idx_leads_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合作意向留资';
